### ISSUE TITLE
JaCoCo

### ISSUE THREAD

**Issue by OleksandrKucherenko** [googlesamples/android-testing-templates#7]
> Note: Generating JaCoCo reports from command-line via Gradle for the app module is currently not working: [https://code.google.com/p/android/issues/detail?id=144664]

Please use my articles for fixing that:
- https://github.com/OleksandrKucherenko/EspressoTestCoverageApp
- https://plus.google.com/+OleksandrKucherenko/posts/VvykyMrkDMT
- https://plus.google.com/+OleksandrKucherenko/posts/6vNWkkLed3b

**Comment by slinzner** [comment]
Closing this bug since it is not template related. We fixed code coverage in 0.4 of the runner. Coverage reports are now create for instrumentation tests. There is still the tools issue (https://code.google.com/p/android/issues/detail?id=144664) you pointed out above, which prevents coverage reports for unit tests in the app module. If you still feel we are missing something please file a bug against tools (https://code.google.com/p/android/issues/list?q=label:Subcomponent-Tools-test-support) or atsl (https://code.google.com/p/android/issues/list?can=1&q=label%3AComponent-Test-Support-Libraries&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles)
